FROM node:20

WORKDIR /web

COPY package.json /web/package.json
RUN npm install

# Install Chromium and all required system libraries for Playwright
RUN npx playwright install --with-deps chromium

COPY . /web/
